### PR TITLE
Give an ever so slightly nicer "Density of States" label

### PR DESCRIPTION
**Pull request by kavanase**

### CODE REVIEW

**Comment by kbspooner** [comment]
That does look better with the dos-style, plots, although the single-line option is probably better with full-size plots... I'm thinking maybe `labels` should be reserved for full-size plots, I could add a `small_labels` function, which has this and things like &kappa;<sub>l</sub> for this purpose. Perhaps this 'small_labels' function could be automatically used when the `invert` argument is used, or maybe thats too presumptous...

**Comment by kavanase** [comment]
Yep good point. I was thinking that when I made the PR, and had a quick flick through the examples and couldn't see any full-size DOS plots (with the "Density of States" x-axis label), so wasn't sure if they were really a thing in the phonon world. I think something along the lines of what you suggest (i.e. intelligent defaults), but also keeping it as an optional argument if possible?

**Comment by kbspooner** [comment]
Yeah that sounds good, it can be another two functions like this:
```python
def style():
    """Get default style sheet."""
    return 'tp'
```
one for normal axes labels and another for inverted labels, where the user can easily change `labels()` for `small_labels()` or vice versa, and if someone has their own labeling style they can add that in as well (which is after all the intended purpose of the settings module). And it can always be overwritten on a per-script basis.

**Comment by kavanase** [comment]
Looks good! 👌

**Pull request closed without merging**
